language: java
sudo: false
install: true

addons:
  sonarqube:
    token:
      secure: "11c112b59ed9780b2effc35bde71e6f4650ad8d0"

jdk:
  - oraclejdk8

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
  email: false